### ISSUE TITLE
how to handle chinese( utf-8)

### ISSUE THREAD

**Issue by awenhu** [jupyter-server/kernel_gateway#194]
I using the kernel gateway in jupyter notebook, when I test the api,  cannot display chinese correctly.

**Comment by parente** [comment]
Can you provide an example notebook and state how you're running the kernel gateway so that we can use it to debug and create a test?

**Comment by parente** [comment]
@awenhu I'm going to close this issue as inactive. If you can provide a sample notebook to help us debug, please feel free to reopen the issue.

**Comment by PetraWang** [comment]
sorry to re-open it, but I`ve encountered the same issue.
Here`s my sample notebook content
`# GET /contacts
import json
req = json.loads(REQUEST)
print(req)
print("test")
print("测试")`

I used command below to start the server:
`jupyter-kernelgateway --KernelGatewayApp.api='kernel_gateway.notebook_http' --Kerne
lGatewayApp.seed_uri='api_intro.ipynb'`

And when I tested the api with
`http://127.0.0.1:8889/contacts?name=1`
I got 
![image](https://user-images.githubusercontent.com/16718430/43881262-365d583c-9bde-11e8-994d-93ed40cdc92d.png)

**Comment by PetraWang** [comment]
[api_intro2.zip](https://github.com/jupyter/kernel_gateway/files/2301261/api_intro2.zip)
Thanks for the reply @rolweber 
Since github does not support uploading ipynb file, I uploaded the zipped file as attachment.

The characters I wanted to print is '测试' which means 'test' in english, and the outcome was '娴嬭瘯' which I cannot get the meaning.

I was running my test on Windows10, Python3.6. I started the jupyter-kernelgateway via Windows PowerShell. I`m not sure whether that matters. 

Thanks

**Comment by rolweber** [comment]
Thanks @PetraWang, zipping the file was the best approach to attach it :-)

Character encodings are a tricky thing. Assuming the characters are encoded correctly in your ipynb file (which I didn't check yet, for lack of time):
1. The ipynb file is loaded by kernel gateway into RAM.
2. The characters are sent in the response to your request. (server side)
3. The characters are received with the response to your request. (client side)
4. The characters are printed in your shell.

Each of these steps might apply an incorrect encoding, leading to garbled characters.

Could you do some more debugging on the client side? It would be interesting to know:
- The HTTP headers returned in the response to your request.  
  In particular the `Content-Type` and `Content-Length` headers, if they are present.
- A hexdump of the response body.  
  This eliminates step 4 and provides an exact representation of the binary response data.

**Comment by LukeWang163** [comment]
> Thanks @PetraWang, zipping the file was the best approach to attach it :-)
> 
> Character encodings are a tricky thing. Assuming the characters are encoded correctly in your ipynb file (which I didn't check yet, for lack of time):
> 
> 1. The ipynb file is loaded by kernel gateway into RAM.
> 2. The characters are sent in the response to your request. (server side)
> 3. The characters are received with the response to your request. (client side)
> 4. The characters are printed in your shell.
> 
> Each of these steps might apply an incorrect encoding, leading to garbled characters.
> 
> Could you do some more debugging on the client side? It would be interesting to know:
> 
> * The HTTP headers returned in the response to your request.
>   In particular the `Content-Type` and `Content-Length` headers, if they are present.
> * A hexdump of the response body.
>   This eliminates step 4 and provides an exact representation of the binary response data.

It turns out that we built the docker image withou setting right locale…

**Comment by kevin-bates** [comment]
Looks like this was ultimately resolved - user config issue - closing.

> It turns out that we built the docker image withou setting right locale…
