### ISSUE TITLE
Moving repo to jupyter-server org

### ISSUE THREAD

**Issue by kevin-bates** [jupyter-server/kernel_gateway#373]
It's time we transfer the Kernel Gateway repo to the [jupyter-server organization](https://github.com/jupyter-server) per the new governance model.  Here's the team-compass issue that contains appropriate references: https://github.com/jupyter-server/team-compass/issues/20

@parente - I just discovered I don't have adequate permissions to transfer the repo.  Are you able to grant me the appropriate privileges or perform the transfer yourself (since your SCC membership, I believe, gives you adequate rights in jupyter-server)?

Thank you.

**Comment by parente** [comment]
Hi @kevin-bates. I've made you an admin on this repo so you can perform the transfer. Cheers!

**Comment by kevin-bates** [comment]
Thank @parente.  We are now in the Jupyter Server organization: https://github.com/jupyter-server/kernel_gateway

No action should be necessary for any of our members.  I suppose you could update your remote reference to "upstream" to point at `jupyter-server`, although `git` will auto-forward for you:
```bash
git remote set-url upstream https://github.com/jupyter-server/kernel_gateway.git
```
